name: Build and Deploy Frontend

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Match your environment

    - name: npm install, build, and test
      run: |
          cd crop-disease-detection-frontend
          npm install --legacy-peer-deps
          npm run build --if-present
          npm run test --if-present


    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: crop-disease-detection-frontend/build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'plant-disease-frontend'  # Azure app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: 'crop-disease-detection-frontend/build'
