name: Build and Deploy Frontend

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use a compatible Node.js version
    
    - name: Install Dependencies and Build
      run: |
        cd crop-disease-detection-frontend  # Point to the correct folder
        npm install
        npm run build --if-present
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'plant-disease-frontend'  # Your Azure frontend app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: 'crop-disease-detection-frontend/build'  # Deploy the build folder
